CREATE TABLE Products (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Price DECIMAL(18,2) NOT NULL,
    Category NVARCHAR(50) NOT NULL,
    Description NVARCHAR(500),
    Stock INT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
)